// <auto-generated />
using AnimeHubApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeHubApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250925111809_AddAllGenres")]
    partial class AddAllGenres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeHub.Shared.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Episodes")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Animes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Masashi Kishimoto",
                            CategoryId = 1,
                            Description = "Ninja action adventure",
                            Episodes = 500,
                            Rating = 9.0,
                            Title = "Naruto Shippuden",
                            YearPublished = 2007
                        },
                        new
                        {
                            Id = 2,
                            Author = "Koyoharu Gotouge",
                            CategoryId = 1,
                            Description = "Fantasy action adventure",
                            Episodes = 55,
                            Rating = 9.1999999999999993,
                            Title = "Demon Slayer: Kimetsu no Yaiba",
                            YearPublished = 2019
                        },
                        new
                        {
                            Id = 3,
                            Author = "Studio Ghibli",
                            CategoryId = 2,
                            Description = "Fantasy adventure movie",
                            Episodes = 1,
                            Rating = 9.5,
                            Title = "Spirited Away",
                            YearPublished = 2001
                        });
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.AnimeGenre", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("AnimeId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("AnimeGenres");

                    b.HasData(
                        new
                        {
                            AnimeId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            AnimeId = 1,
                            GenreId = 3
                        },
                        new
                        {
                            AnimeId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            AnimeId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            AnimeId = 3,
                            GenreId = 2
                        },
                        new
                        {
                            AnimeId = 3,
                            GenreId = 3
                        });
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TV Series"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Movie"
                        },
                        new
                        {
                            Id = 3,
                            Name = "OVA"
                        });
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cars"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dementia"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Demons"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ecchi"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Game"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Harem"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Isekai"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Josei"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Kids"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Magic"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Martial Arts"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Mecha"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Military"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Parody"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Police"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Psychological"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Samurai"
                        },
                        new
                        {
                            Id = 28,
                            Name = "School"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Seinen"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Shoujo"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Shoujo Ai"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Shounen"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Shounen Ai"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Slice of Life"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Space"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Super Power"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Supernatural"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Vampire"
                        });
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.Anime", b =>
                {
                    b.HasOne("AnimeHub.Shared.Models.Category", "Category")
                        .WithMany("Animes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.AnimeGenre", b =>
                {
                    b.HasOne("AnimeHub.Shared.Models.Anime", "Anime")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeHub.Shared.Models.Genre", "Genre")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.Anime", b =>
                {
                    b.Navigation("AnimeGenres");
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.Category", b =>
                {
                    b.Navigation("Animes");
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.Genre", b =>
                {
                    b.Navigation("AnimeGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
