// <auto-generated />
using System;
using AnimeHubApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeHubApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251204052707_AddUserAnimeTable")]
    partial class AddUserAnimeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeHub.Shared.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Episodes")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PremieredYear")
                        .HasColumnType("int");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("Season")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrailerPosterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Animes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Ninja action adventure",
                            Episodes = 500,
                            PremieredYear = 2007,
                            Rating = 9.0,
                            Season = 1,
                            Status = 3,
                            Title = "Naruto Shippuden"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Fantasy action adventure",
                            Episodes = 55,
                            PremieredYear = 2019,
                            Rating = 9.1999999999999993,
                            Season = 2,
                            Status = 3,
                            Title = "Demon Slayer: Kimetsu no Yaiba"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Fantasy adventure movie",
                            Episodes = 1,
                            PremieredYear = 2001,
                            Rating = 9.5,
                            Season = 3,
                            Status = 3,
                            Title = "Spirited Away"
                        });
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.AnimeGenre", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("AnimeId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("AnimeGenres");

                    b.HasData(
                        new
                        {
                            AnimeId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            AnimeId = 1,
                            GenreId = 3
                        },
                        new
                        {
                            AnimeId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            AnimeId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            AnimeId = 3,
                            GenreId = 2
                        },
                        new
                        {
                            AnimeId = 3,
                            GenreId = 3
                        });
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.AnimeStudio", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("int");

                    b.Property<int>("StudioId")
                        .HasColumnType("int");

                    b.HasKey("AnimeId", "StudioId");

                    b.HasIndex("StudioId");

                    b.ToTable("AnimeStudios");

                    b.HasData(
                        new
                        {
                            AnimeId = 1,
                            StudioId = 1
                        },
                        new
                        {
                            AnimeId = 2,
                            StudioId = 2
                        },
                        new
                        {
                            AnimeId = 3,
                            StudioId = 3
                        });
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TV Series"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Movie"
                        },
                        new
                        {
                            Id = 3,
                            Name = "OVA"
                        });
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cars"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cyberpunk"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Dementia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Demons"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dystopian"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ecchi"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Game"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Gore"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Harem"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Isekai"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Josei"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Kids"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Magic"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Martial Arts"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Mecha"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Military"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Parody"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Police"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Psychological"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Samurai"
                        },
                        new
                        {
                            Id = 31,
                            Name = "School"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Seinen"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Shoujo"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Shoujo Ai"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Shounen"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Shounen Ai"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Slice of Life"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Space"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Super Power"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Supernatural"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Suspense"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Time Travel"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Tragedy"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Vampire"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Workplace"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Yaoi"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Yuri"
                        });
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "8bit"
                        },
                        new
                        {
                            Id = 2,
                            Name = "A-1 Pictures"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bones"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CloverWorks"
                        },
                        new
                        {
                            Id = 5,
                            Name = "David Production"
                        },
                        new
                        {
                            Id = 6,
                            Name = "J.C.STAFF"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kyoto Animation"
                        },
                        new
                        {
                            Id = 8,
                            Name = "LIDENFILMS"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Madhouse"
                        },
                        new
                        {
                            Id = 10,
                            Name = "MAPPA"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Production I.G"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Silver Link."
                        },
                        new
                        {
                            Id = 13,
                            Name = "Studio DEEN"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Studio Ghibli"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Studio Pierrot"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Sunrise"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Toei Animation"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Trigger"
                        },
                        new
                        {
                            Id = 19,
                            Name = "ufotable"
                        },
                        new
                        {
                            Id = 20,
                            Name = "White Fox"
                        });
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.UserAnime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("UserId", "AnimeId")
                        .IsUnique();

                    b.ToTable("UserAnimes");
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.UserAnimeRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("AnimeId", "UserId")
                        .IsUnique();

                    b.ToTable("UserAnimeRatings");
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.Anime", b =>
                {
                    b.HasOne("AnimeHub.Shared.Models.Category", "Category")
                        .WithMany("Animes")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.AnimeGenre", b =>
                {
                    b.HasOne("AnimeHub.Shared.Models.Anime", "Anime")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeHub.Shared.Models.Genre", "Genre")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.AnimeStudio", b =>
                {
                    b.HasOne("AnimeHub.Shared.Models.Anime", "Anime")
                        .WithMany("AnimeStudios")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeHub.Shared.Models.Studio", "Studio")
                        .WithMany("AnimeStudios")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.UserAnime", b =>
                {
                    b.HasOne("AnimeHub.Shared.Models.Anime", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeHub.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.UserAnimeRating", b =>
                {
                    b.HasOne("AnimeHub.Shared.Models.Anime", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeHub.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.Anime", b =>
                {
                    b.Navigation("AnimeGenres");

                    b.Navigation("AnimeStudios");
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.Category", b =>
                {
                    b.Navigation("Animes");
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.Genre", b =>
                {
                    b.Navigation("AnimeGenres");
                });

            modelBuilder.Entity("AnimeHub.Shared.Models.Studio", b =>
                {
                    b.Navigation("AnimeStudios");
                });
#pragma warning restore 612, 618
        }
    }
}
