// <auto-generated />
using AnimeHubApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeHubApi.Migrations
{
    [DbContext(typeof(AnimeDbContext))]
    [Migration("20250826081630_SeedingTable")]
    partial class SeedingTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeHubApi.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Episodes")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Animes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Episodes = 500,
                            Genre = "Action/Adventure",
                            Title = "Naruto Shippuden",
                            YearPublished = 2007
                        },
                        new
                        {
                            Id = 2,
                            Episodes = 55,
                            Genre = "Action/Fantasy",
                            Title = "Demon Slayer",
                            YearPublished = 2019
                        },
                        new
                        {
                            Id = 3,
                            Episodes = 47,
                            Genre = "Action/Supernatural",
                            Title = "Jujutsu Kaisen",
                            YearPublished = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
